/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_covisint_platform_device_pi_jni_Buzzer */

#ifndef _Included_com_covisint_platform_device_pi_jni_Buzzer
#define _Included_com_covisint_platform_device_pi_jni_Buzzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_covisint_platform_device_pi_jni_Buzzer
 * Method:    on
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_covisint_platform_device_pi_jni_Buzzer_on
  (JNIEnv *, jobject);

/*
 * Class:     com_covisint_platform_device_pi_jni_Buzzer
 * Method:    off
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_covisint_platform_device_pi_jni_Buzzer_off
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
