/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_covisint_platform_device_pi_jni_Led */

#ifndef _Included_com_covisint_platform_device_pi_jni_Led
#define _Included_com_covisint_platform_device_pi_jni_Led
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_covisint_platform_device_pi_jni_Led
 * Method:    on
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_covisint_platform_device_pi_jni_Led_on
  (JNIEnv *, jobject);

/*
 * Class:     com_covisint_platform_device_pi_jni_Led
 * Method:    off
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_covisint_platform_device_pi_jni_Led_off
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
