/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_covisint_platform_device_pi_jni_StatusLight */

#ifndef _Included_com_covisint_platform_device_pi_jni_StatusLight
#define _Included_com_covisint_platform_device_pi_jni_StatusLight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_covisint_platform_device_pi_jni_StatusLight
 * Method:    setColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_covisint_platform_device_pi_jni_StatusLight_setColor
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
